# --- 0. Creación del Namespace (Nuevo) ---
apiVersion: v1
kind: Namespace
metadata:
  name: app-edugitops
---
# --- 1. Identidad (ServiceAccount) ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-edugitops-sa      # CAMBIO: flask-minikube-sa -> app-edugitops-sa
  namespace: app-edugitops
---
# --- 2. Permisos (RBAC) ---
# El ClusterRole es global, no lleva namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-viewer-role
rules:
- apiGroups: ["", "apps"]
  resources: ["services", "pods", "deployments", "nodes", "namespaces"] 
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-viewer-binding
subjects:
- kind: ServiceAccount
  name: app-edugitops-sa      # CAMBIO: Coincide con el nuevo nombre del SA
  namespace: app-edugitops
roleRef:
  kind: ClusterRole
  name: service-viewer-role
  apiGroup: rbac.authorization.k8s.io
---
# --- 3. La Aplicación (Deployment) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-edugitops         # CAMBIO: flask-k8s-app -> app-edugitops
  namespace: app-edugitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-edugitops      # CAMBIO: flask-k8s -> app-edugitops
  template:
    metadata:
      labels:
        app: app-edugitops    # CAMBIO: flask-k8s -> app-edugitops
    spec:
      serviceAccountName: app-edugitops-sa # CAMBIO: flask-minikube-sa -> app-edugitops-sa
      containers:
      - name: app-edugitops   # CAMBIO: flask -> app-edugitops (por coherencia)
        image: soygonzalodeniz/app-edugitops:1.3
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_PORT
          value: "5001"
        - name: FLASK_DEBUG
          value: "${FLASK_DEBUG}"          
        
        # Variables de Gitea (Asegúrate de que sean correctas para tu entorno)
        - name: GITEA_API_URL
          value: "http://gitea.gitea.svc.cluster.local:80/api/v1" 
        - name: GITEA_REPO_OWNER
          value: "admin"
        - name: GITEA_REPO_NAME
          value: "demo-tfm"
        - name: GITEA_FILE_PATH
          value: "${GITEA_FILE_PATH}"
        - name: GITEA_CATALOGO_PATH
          value: "${GITEA_CATALOGO_PATH}"         
        - name: GITEA_BRANCH
          value: ${GITEA_BRANCH}
        - name: GITEA_USER
          value: "${GITEA_USER}"
        - name: GITEA_PASSWORD 
          value: "${GITEA_PASSWORD}"
---
# --- 4. Acceso de Red (Service) ---
apiVersion: v1
kind: Service
metadata:
  name: app-edugitops
  namespace: app-edugitops
spec:
  type: NodePort
  selector:
    app: app-edugitops        # CAMBIO: flask-k8s -> app-edugitops (Vital para que encuentre los pods)
  ports:
    - protocol: TCP
      port: 5001      
      targetPort: 5001
      # nodePort: 30001 # Opcional