apiVersion: v1
kind: Namespace
metadata:
  name: checkmk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmk
  namespace: checkmk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmk
  template:
    metadata:
      labels:
        app: checkmk
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: checkmk
          image: checkmk/check-mk-raw:2.4.0p16
          imagePullPolicy: IfNotPresent
          env:
            - name: CMK_SITE_ID
              value: cmk
            - name: CMK_PASSWORD
              value: "admin123"
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 6557
              name: livestatus
          
          # --- MEJORA: Definición de recursos ---
          resources:
            requests:
              memory: "512Mi" # Garantiza RAM mínima
              cpu: "300m"     # Garantiza ciclo de CPU para arrancar
            limits:
              memory: "2Gi"   # Evita que colapse el nodo
              cpu: "1000m"

          volumeMounts:
            - name: data
              mountPath: /omd/sites
          
          # --- MEJORA: Probes más pacientes ---
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5      # IMPORTANTE: espera 5s respuesta
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 180 # Checkmk tarda en crear el 'site'
            periodSeconds: 20
            timeoutSeconds: 5      # IMPORTANTE
            failureThreshold: 10   # Aguanta 10 fallos antes de matar
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: checkmk
  namespace: checkmk
spec:
  # CAMBIO: NodePort para compatibilidad AWS Academy/Minikube
  type: NodePort
  selector:
    app: checkmk
  ports:
    - name: http
      port: 80
      targetPort: 5000
    - name: livestatus
      port: 6557
      targetPort: 6557