apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
# ELIMINADO: PersistentVolumeClaim (No tienes permisos)
# Usaremos emptyDir en el Deployment directamente.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-appini
  namespace: gitea
data:
  app.ini: |
    APP_NAME = Gitea
    RUN_MODE = prod
    RUN_USER = git

    [database]
    DB_TYPE = sqlite3
    PATH = /data/gitea/gitea.db

    [repository]
    ROOT = /data/git/repositories

    [lfs]
    STORAGE_TYPE = local
    PATH = /data/git/lfs

    [server]
    PROTOCOL = http
    DOMAIN = localhost
    HTTP_PORT = 3000
    ROOT_URL = http://localhost:3000/
    # Nota: En EKS, después de desplegar, podrías querer cambiar 
    # ROOT_URL y DOMAIN con la dirección del LoadBalancer generado.

    [log]
    ROOT_PATH = /data/gitea/log

    [security]
    INSTALL_LOCK = true
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin
  namespace: gitea
type: Opaque
stringData:
  username: admin
  password: admin123
  email: admin@example.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      securityContext:
        fsGroup: 1000

      initContainers:
        - name: init-gitea-config
          image: busybox:1.36
          command: ["sh", "-ceu"]
          args:
            - |
              mkdir -p /data/gitea/conf /data/gitea/log /data/git/repositories /data/git/lfs /data/git/.ssh
              chmod 700 /data/git/.ssh || true

              if [ ! -f /data/gitea/conf/app.ini ]; then
                cp /config/app.ini /data/gitea/conf/app.ini
              fi

              if ! grep -q '^SECRET_KEY' /data/gitea/conf/app.ini; then
                echo "SECRET_KEY = $(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)" >> /data/gitea/conf/app.ini
              fi
              if ! grep -q '^INTERNAL_TOKEN' /data/gitea/conf/app.ini; then
                echo "INTERNAL_TOKEN = $(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 40)" >> /data/gitea/conf/app.ini
              fi

              chown -R 1000:1000 /data/gitea /data/git
          volumeMounts:
            - name: data
              mountPath: /data
            - name: appini
              mountPath: /config
              readOnly: true

        - name: init-gitea-admin
          image: docker.gitea.com/gitea:1.25.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"    # Garantiza 1/4 de núcleo para arrancar
            limits:
              memory: "1Gi"  # Evita que se coma toda la RAM si hay fuga
              cpu: "1000m"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: HOME
              value: /data/gitea
            - name: GITEA_WORK_DIR
              value: /data/gitea
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gitea-admin
                  key: username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-admin
                  key: password
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: gitea-admin
                  key: email
          command: ["/bin/sh", "-ceu"]
          args:
            - |
              set -euo pipefail
              gitea --config /data/gitea/conf/app.ini migrate
              if gitea --config /data/gitea/conf/app.ini admin user create \
                   --username "${ADMIN_USERNAME}" \
                   --password "${ADMIN_PASSWORD}" \
                   --email "${ADMIN_EMAIL}" \
                   --admin \
                   --must-change-password=false; then
                echo "Admin creado."
              else
                echo "Actualizando contraseña admin."
                gitea --config /data/gitea/conf/app.ini admin user change-password \
                  --username "${ADMIN_USERNAME}" \
                  --password "${ADMIN_PASSWORD}"
              fi
          volumeMounts:
            - name: data
              mountPath: /data

      containers:
        - name: gitea
          image: docker.gitea.com/gitea:1.25.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: GITEA_CUSTOM
              value: /data/gitea
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /api/healthz  
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 15     
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /api/healthz  
              port: http
            initialDelaySeconds: 180 
            periodSeconds: 20 
            timeoutSeconds: 15
            failureThreshold: 10

      volumes:
        - name: data
          emptyDir: {} 
        - name: appini
          configMap:
            name: gitea-appini
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  type: LoadBalancer
  selector:
    app: gitea
  ports:
    - name: http
      port: 80       
      targetPort: 3000