{{- if has "grafana" .Values.apps }}
# --- 1. Secret (Credenciales Admin) ---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Values.nombre }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
---
# --- 2. ConfigMap (Provisioning de Datasources) ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: {{ .Values.nombre }}
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.{{ .Values.nombre }}.svc:9090
        isDefault: true
---
# --- 3. Deployment (Aplicación) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.nombre }}
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana-oss:latest
          envFrom:
            - secretRef:
                name: grafana-admin
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: provisioning
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: provisioning
          configMap:
            name: grafana-configmap
---
# --- 4. Service (Acceso de Red) ---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: {{ .Values.nombre }}
spec:
  selector:
    app: grafana  
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
{{- end }}