{{- if has "apache" .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
  namespace: {{ .Values.nombre }}
spec:
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:alpine
        ports:
        - containerPort: 80
{{- end }}