{{- if has "grafana" .Values.apps }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{ .Values.nombre }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Mi
{{- end }}
