{{- if has "nginx" .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: {{ .Values.nombre }}
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
{{- end }}