# Recurso Ingress en Kubernetes para exponer Prometheus externamente a través de un controlador Ingress (nginx) en el namespace demo-monitoring.


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: demo-monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: prometheus.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
