# Recurso ConfigMap en Kubernetes llamado grafana-datasource dentro del namespace demo-monitoring.
# El ConfigMap contiene la configuración de la fuente de datos para Grafana en la clave datasource.yml.
# Esta configuración indica que Grafana debe conectarse a Prometheus
# (usando la URL http://prometheus.monitoring.svc:9090) como fuente de datos principal
# (isDefault: true) mediante acceso tipo proxy.

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: monitoring-{{alumno}}-{{id_alumno}}
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc:9090
        isDefault: true
