apiVersion: v1
kind: Namespace
metadata:
  name: checkmk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkmk-data
  namespace: checkmk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmk
  namespace: checkmk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmk
  template:
    metadata:
      labels:
        app: checkmk
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: checkmk
          image: checkmk/check-mk-raw:2.4.0p16
          imagePullPolicy: IfNotPresent
          env:
            - name: CMK_SITE_ID
              value: cmk
            - name: CMK_PASSWORD
              value: "admin123"
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 6557
              name: livestatus
          volumeMounts:
            - name: data
              mountPath: /omd/sites
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 90
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 120
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: checkmk-data
---
apiVersion: v1
kind: Service
metadata:
  name: checkmk
  namespace: checkmk
spec:
  type: NodePort
  selector:
    app: checkmk
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
    - name: livestatus
      port: 6557
      targetPort: 6557
      nodePort: 30657
