
# Recurso Service en Kubernetes para exponer Grafana dentro del namespace monitoring-<alumno>-<id_alumno>.
#
# El servicio es de tipo NodePort y selecciona los pods con la etiqueta app: grafana.
# Expone el puerto 30001 para acceder a la interfaz web de Grafana.


apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring-ana-001
spec:
  selector: {app: grafana}
  type: NodePort
  ports:
    - protocol: tcp
      port: 3000        # Puerto interno del servicio
      targetPort: 3000  # Puerto dentro del contenedor
      nodePort: 30001 # Puerto expuesto en el nodo (personalizable por alumno) Rango: 30000–32767.
  




