{{- if has "grafana" .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: {{ .Values.nombre }}
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: {{ printf "30%s" .Values.id | int }}
{{- end }}
