{{- if eq (include "monitoring.boolEnabled" .Values.grafana.enabled) "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
