# Recurso Deployment en Kubernetes para desplegar Prometheus en el namespace demo-monitoring.
#
# El deployment crea un pod con un contenedor basado en la imagen prom/prometheus:latest.
# El contenedor expone el puerto 9090 y utiliza dos volúmenes:
# - Un ConfigMap llamado prometheus-config montado en /etc/prometheus/prometheus.yml para la configuración de Prometheus.
# - Un PersistentVolumeClaim llamado prometheus-data montado en /prometheus para el almacenamiento de datos.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring-{{alumno}}-{{id_alumno}}
spec:
  replicas: 1
  selector:
    matchLabels: {app: prometheus}
  template:
    metadata:
      labels: {app: prometheus}
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-data
