# Recurso Service en Kubernetes para exponer Grafana dentro del cluster en el namespace demo-monitoring.

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: demo-monitoring
spec:
  type: ClusterIP
  selector: {app: grafana}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  